import Link from "next/link";
import { PageShell } from "@/components/site-shell";
import { PortfolioIntro, RelatedWork } from "@/components/portfolio-editorial";
import { metadataFor } from "@/lib/site-metadata";

export const metadata = metadataFor("/research/microstructure", "Market Microstructure and Replay", "Current work on multi-venue public market data, deterministic C++ replay, fill uncertainty, adverse selection, and short-horizon execution research.");

export default function MicrostructurePage() {
  return <PageShell><article className="folio">
    <PortfolioIntro eyebrow="Current work / Market microstructure" title="What happens between a signal and a fill?"><p>My current work moves beyond faster bar indicators to event-level market mechanics: order flow, liquidity, queue uncertainty, and price behavior around hypothetical execution.</p></PortfolioIntro>
    <div className="folio-wrap"><div className="folio-note"><strong>Research and engineering in progress.</strong><p>The replay and evaluation tools exist. A robust profitable execution strategy has not been established. Public-data fill proxies are not actual executions.</p></div></div>
    <section className="folio-wrap folio-section folio-two-column"><div><p className="folio-eyebrow">The research question</p><h2>Does the opportunity survive execution?</h2><p>I study whether observable order-flow and liquidity states contain enough information to improve short-horizon execution decisions after accounting for fill uncertainty, adverse selection, and costs.</p><p>The 5-minute and 1-minute studies remain useful context and benchmarks. Event-level data answer a different question rather than automatically upgrading those earlier results.</p></div><div><p className="folio-eyebrow">The engineering contribution</p><h2>A replayable market-data record.</h2><p>The C++ core captures and reconstructs public trades and order-book updates with explicit sequence and timestamp discipline. Deterministic replay makes it possible to compare experiments against the same recorded market events.</p><p>Python research layers examine fill proxies, post-fill markouts, and cost-aware decision rules. Local compute benchmarking has been performed, but it is not a measurement of exchange or end-to-end execution latency.</p></div></section>
    <section className="folio-build-band"><div className="folio-wrap folio-build-grid"><div><p className="folio-eyebrow">System map</p><h2>Observation first.<br />Claims second.</h2><p>These components support research. The diagram is not a live order-routing pipeline, and the website has no trading controls.</p><div className="folio-links"><Link href="/projects">Explore the system layers ↗</Link></div></div><div className="folio-stack"><div><span>Input</span><strong>Multi-venue public events</strong><p>Raw trades and order-book updates.</p></div><div><span>Validation</span><strong>Canonical state and replay</strong><p>Sequence checks, book reconstruction, and deterministic output.</p></div><div><span>Research</span><strong>Execution diagnostics</strong><p>Fill uncertainty, markouts, adverse selection, and costs.</p></div></div></div></section>
    <section className="folio-wrap folio-section"><div className="folio-reading"><h2>Negative tests are part of the deliverable.</h2><p>Recent development screens have not established robust positive execution economics. Improvements relative to an unfavorable baseline do not become profitable strategies merely because the relative comparison is positive.</p><p>I retain failed or inconclusive tests instead of presenting engineering throughput, model accuracy, or hypothetical fills as investment returns. Frozen studies remain frozen; this portfolio does not open protected research samples.</p><h2>What is public.</h2><p>This page describes the research question, engineering responsibilities, and evidence status. Proprietary coefficients, decision thresholds, raw event records, and execution details are not published here.</p><p>Editorial status reviewed on September 26, 2026. This is a dated research summary, not a live system-health feed.</p></div><RelatedWork><Link href="/projects#market-data">Market-data and replay core ↗</Link><Link href="/research/trader-behavior">Behavioral research ↗</Link><Link href="/projects#execution-gateway">Execution engineering boundaries ↗</Link></RelatedWork></section>
  </article></PageShell>;
}
